version: '3.3'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb_lock_wait_timeout=2
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: K79WEY69q8MR1uSx
    ports:
      - '3306:3306'
  mail:
    image: blueimp/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    image: rails-tutorial/rails:latest
    environment:
      - TZ=Asia/Tokyo
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_NAME=rails-tutorial_development
      - DATABASE_USER=root
      - DATABASE_PASSWORD=K79WEY69q8MR1uSx
      - MAILER_URL_PORT=3000
      - SMTP_ADDRESS=mail
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    links:
      - db
      - mail
    stdin_open: true
    tty: true
volumes:
  bundle:
  mysql-data:
  redis-data:
    driver: local
